package com.aaronfleshner.usadivinghelix;

import android.content.Context;

import com.aaronfleshner.usadivinghelix.models.DtoDiver;

import java.util.ArrayList;

/**
 * Created by aaronfleshner on 7/20/14.
 */
public class Divers {

    static ArrayList<DtoDiver> divers;

    public Divers(Context mCxt) {
        divers = new ArrayList<DtoDiver>();
        divers.add(new DtoDiver(mCxt));
//        String imgUrl,
//        String firstName,
//        String lastName,
//        String height,
//        String birthDate,
//        String birthPlace,
//        String homeTown,
//        String currentResidence,
//        String education,
//        String degree,
//        String club,
//        String trains,
//        String coach,
//        ArrayList<String> nationalTeam,
//        String biography,
//        String results
        divers.add(new DtoDiver("http://www.usadiving.org/wp-content/uploads/2013/09/Abby-Johnston.jpg",
                "http://image.cdnllnwnl.xosnetwork.com/pics32/800/KY/KYKDZHDXSBDNKZP.20110719151743.jpg",
                "Abby", "Johnston", "5’ 5″", "November 16, 1989", "Columbus, Ohio", "", "", "Duke University",
                "", "Unattached", "", "Drew Johansen", nationalTeamMemeber("2006, 2008, 2009, 2010, 2011, 2012, 2014"),
                "The daughter of David and Elaine Johnston, Abby has two sisters, Adrienne and Leah, and began diving in 2002. She was also a gymnast for nine years, but had to quit because of a back injury. While an undergraduate at Duke, Abby was enrolled in a pre-med program called CAPE and interned in the brain tumor clinic at Duke Hospital. In the fall of 2014, she will begin medical school at Duke. She enjoys going to the beach, watching TV, playing tennis and soccer, and spending time with family and friends.", ""));
        divers.add(new DtoDiver("http://www.usadiving.org/wp-content/uploads/2013/09/Amanda-Burke.jpg",
                "http://www3.pictures.zimbio.com/gi/USA+Diving+Grand+Prix+fklHmQiQmkRx.jpg",
                "Amanda", "Burke", "", "May 24, 1987", "", "Southampton, Pa.", "State College, Pa.", "Rider University",
                "Communications", "Unattached", "", "Dennis Ceppa", nationalTeamMemeber("2012, 2013, 2014"),
                "The daughter of Karen and Richard Burke, Amanda has a younger sister, Allison. Amanda started diving in 1993 and her favorite dive is 5152B. Her favorite diver is Thomas Finchum. Amanda trained at the USA Diving National Training Center for a year after finishing her collegiate career at Rider University and now trains in State College, Pa., where her college coach, Dennis Ceppa, is now the coach at Penn State. She was the 2010 ECAC champion on 3-meter and was a three-time Rider Female Athlete of the Year. Amanda never competed at the junior level and didn’t start diving 3-meter until 2006. She enjoys music, lifting, shopping and being with friends.", ""));
        divers.add(new DtoDiver("http://0.tqn.com/d/diving/1/5/i/J/-/-/James_Anna.jpg",
                "http://www1.pictures.zimbio.com/gi/Anna+James+Diving+Day+Three+14th+FINA+World+_ZJPgdaT3pQl.jpg",
                "Anna",
                "James",
                "5’ 3”",
                "October 25, 1995",
                "Austin, Texas",
                "Midland, Texas",
                "",
                "Midland HS",
                "",
                "City of Midland Aquatics",
                "",
                "John Proctor",
                nationalTeamMemeber("2011, 2012, 2014"),
                "Anna is the daughter of Christy and Steve James She has an older brother, Adam. She also has has two dogs. Anna started diving at age 10 and was a gymnast before taking up diving. Her favorite diver is Laura Wilkinson. She is an honor roll student and enjoys playing guitar. Her favorite food is Italian. Will attend Purdue University in the fall of 2014.",
                ""));
        divers.add(new DtoDiver("http://www.usadiving.org/wp-content/uploads/2013/11/Cheyenne-Cousineau.jpg",
                "http://cmsimg.freep.com/apps/pbcsi.dll/bilde?Site=C4&Date=20140601&Category=COL38&ArtNo=306010096&Ref=AR&MaxW=640&Border=0&Jeff-Seidel-Diver-Cheyenne-Cousineau-takes-setbacks-stride-while-chasing-Olympic-dream",
                "Cheyenne",
                "Cousineau",
                "5’ 0”",
                "July 28, 1991",
                "Sylvania, Ohio",
                "Temperance, Mich.",
                "Coral Gables, Fla.",
                "University of Miami",
                "Major: Psychology Minor: Neuroscience",
                "Miami Diving",
                "",
                "Randy Ableman",
                nationalTeamMemeber("2012, 2013, 2014"),
                "Cheyenne is the daughter of Roland and Diane Cousineau, both farmers, and has four siblings – Luke, Lance, Dakota, and Sierra. Her father, Roland, is a seventh generation farmer and is still living on the farm started in 1836. Cheyenne has overcome two stress fractures in the back in 2006 and 2007, and a blood clot and stroke in 2010. Cheyenne is majoring in psychology and would love to become a doctor and be able to go on medical missions around the world. In between dives, she usually listens to music and relaxes. Cheyenne also brings her stuffed dog, Baby, that she has had since she was born to competitions for good luck.",
                ""));
        divers.add(new DtoDiver("http://www.usadiving.org/wp-content/uploads/2013/11/Darian-Schmidt-1-of-2.jpg",
                "http://photos.digitalsports.com/2120971/DSC_0262_Darian_Schmidt_fullview.jpg",
                "Darian",
                "Schmidt",
                "5’ 10”",
                "March 23, 1992",
                "Bloomington, Ind.",
                "",
                "Bloomington, Ind.",
                "Indiana University",
                "Major: Psychology Minor: Neuroscience",
                "Indiana University",
                "",
                "Drew Johansen",
                nationalTeamMemeber("2013, 2014"),
                "The son of Doug and Susan Schmidt, Darien has three younger siblings: Dathan, Daxton and Dallan. Darian started diving at age 14. he quit diving after his freshman year in high school, but his parents asked him to start up again after the late Mark Lenzi took over the club program at Indiana. Once Darian found out that Lenzi was an Olympic champion, he was hooked on the sport. He now trains four to five hours a day six days a week, and his favorite dive is 5353B on 3-meter. A criminal justice major at Indiana University, Darian would like to become a diving coach. His interests include cars and motorcycles.",
                ""));
        divers.add(new DtoDiver("http://www.usadiving.org/wp-content/uploads/2013/09/David-Bonuchi-219x300.jpg",
                "http://bloximages.newyork1.vip.townnews.com/columbiatribune.com/content/tncms/assets/v3/editorial/3/8b/38ba4088-96fb-11e2-8b83-001a4bcf6878/51531df312015.preview-500.jpg",
                "David",
                "Bonuchi",
                "5’ 10”",
                "May 22, 1992",
                "Columbia, Mo.",
                "Columbia, Mo.",
                "Columbia, Mo.",
                "University of Missouri",
                "",
                "Missouri Diving Club",
                "",
                "James Sweeney",
                nationalTeamMemeber("2010, 2011, 2012, 2013"),
                "David is the son of Jim and Kathy Bonuchi. He has two brothers, James and Daniel, and he started diving in 2003. He enjoys cars and snowboarding, and he likes clothes and hopes to become a model. David is active in the Church of Jesus Christ of Latter Day Saints and loves a good joke. His favorite dive is a 305C.",
                ""));
        divers.add(new DtoDiver("http://www.usadiving.org/wp-content/uploads/2013/09/David-Boudia1.jpg",
                "http://www2.pictures.zimbio.com/gi/David+Boudia+Olympics+Day+14+Diving+wdWnq-T-yxXl.jpg",
                "David",
                "Boudia",
                "5’ 9”",
                "April 24, 1989",
                "Abilene, Texas",
                "Noblesville, Ind.",
                "West Lafayette, Ind.",
                "Purdue University",
                "Communications",
                "Boiler Diving",
                "",
                "Adam Soldati",
                nationalTeamMemeber("2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014"),
                "The son of Jim and Sheilagh Boudia, David has two sisters, Shaila and Shauni. In October 2012, he married his wife, Sonnie. They are expecting their first child in September, 2014. David enjoys anything competitive (football, basketball, soccer, etc.), reading, video games, and hanging out with friends. He has been diving since 2000, and learned under Olympic coach John Wingfield up until moving on to Purdue in the fall of 2008. David’s ultimate goal was to win an Olympic gold medal, which he accomplished at the London Games. His favorite dive is 109C.",
                ""));
        divers.add(new DtoDiver("http://www.usadiving.org/wp-content/uploads/2013/11/David-Dinsmore-1-of-2.jpg",
                "http://www.dispatch.com/content/graphics/2012/10/09/junior-diving-art-gm1jnm1v-1junior-diving-kr-04-jpg.jpg",
                "David",
                "Dinsmore",
                "5’ 5”",
                "May 25, 1997",
                "Cincinnati, Ohio",
                "New Albany, Ohio",
                "",
                "New Albany High School",
                "",
                "Ohio State Diving Club",
                "",
                "John Appleman",
                nationalTeamMemeber("2013, 2014"),
                "David is the son of Allan and Stephanie Dinsmore and has one younger brother, Matthew. He has been diving since age nine and his favorite dive in 5253B. He trains five hours a day, five days a week. During the summer, he also coaches community summer league diving. When he is not diving, David enjoys fishing, archery, trapshooting and snowboarding. David also plays the cello. David’s favorite movie is Anchorman.",
                ""));
        divers.add(new DtoDiver("http://www.usadiving.org/wp-content/uploads/2013/11/Deidre-Freeman.jpg",
                "http://fe391d5e875395beaa5c-4d0fcf8d315d40f305ee2ebb6c32f79c.r96.cf1.rackcdn.com/525871_1377015715.9265_upd.jpg",
                "Deidre",
                "Freeman",
                "5’ 4”",
                "August 26, 1988",
                "Grinnell, Iowa",
                "Grinnell, Iowa",
                "Grinnell, Iowa",
                "University of Iowa",
                "",
                "",
                "",
                "Todd Waikel",
                nationalTeamMemeber("2012, 2013, 2014"),
                "Deidre is the daughter of Will and Evelyn Freeman who coach track as well as cross country. Her father represented the U.S. internationally in pole vaulting and attended Olympic trials while her mother attended the Canadian Olympic trials.  Deidre has two siblings, Cameron and Nicolette, and began diving when she was fourteen-years-old. When she is not training, Deidre works as a softball coach at Grinnell High School and a dance instructor at Michelle’s Dance Academy. Trained with the Spanish National Team in 2009 when she spent a semester studying abroad in Madrid. In between dives, Deidre likes to stay warm by walking around and sometimes watching other divers. She is a vegetarian, has an extensive tea collection and is a total tree hugger.",
                ""));
        divers.add(new DtoDiver("http://www.usadiving.org/wp-content/uploads/2013/11/Dwight-Dumais-2.jpg",
                "http://img.spokeo.com/public/900-600/justin_dumais_2012_06_22.jpg",
                "Dwight",
                "Dumais",
                "5’ 7”",
                "June 23, 1986",
                "Ventura, Calif.",
                "Ventura, Calif.",
                "Austin, Texas",
                "Stanford",
                "B.A. in Human Biology",
                "Longhorn Aquatics",
                "",
                "Matt Scoggin",
                nationalTeamMemeber("2012, 2013, 2014"),
                "Dwight is the son of Marc and Kathleen Dumais and has four siblings: Justin, Troy, Brice and Leanne. Dwight has been diving since 1992 and his favorite dive is a 5154B off the 3-meter springboard. During meets he likes to stretch while listening to music or watching a movie. Dwight finds the hardest part of training is the amount of dedication and time commitment it takes. When he is not diving Dwight likes to surf, cook and spend time with friends. He also coaches with Longhorn Aquatics.",
                ""));
        divers.add(new DtoDiver("http://www.usadiving.org/wp-content/uploads/2013/09/Jessica-Parratto.jpg",
                "http://www3.pictures.zimbio.com/gi/Jessica+Parratto+Diving+Day+Five+14th+FINA+St3OgAPvlDnl.jpg",
                "Jessica",
                "Parratto",
                "5’ 2”",
                "June 26, 1994",
                "Dover, N.H.",
                "Dover, N.H.",
                "Bloomington, Ind.",
                "Indiana University",
                "Community Health",
                "Indiana University",
                "",
                "Drew Johansen",
                nationalTeamMemeber("2010, 2011, 2012, 2014"),
                "Jessica is the daughter of Amy and Mike Parratto. She has an older sister, Melissa, who is a swimmer at the University of Pennsylanvia. Her dad is a swim coach and coached Olympic gold medalist swimmer Jenny Thompson, who Jessica says is like a sister to her. Jessica’s mom was a five-time All-American diver at Wellesley College and was Jessica’s coach until she was 14. Jessica started diving when she was 5 and moved to Indianapolis from New Hampshire in 2009 due to limited facilities (her pool had only one 1-meter springboard). She has since become one of the top 10-meter platform divers in the country. Jessica’s favorite dive is 626C, and her favorite diver is Laura Wilkinson. Between dives, she listens to music and relaxes. She enjoys hanging out with friends, going to the beach, and outdoor activities. Previously, Jessica also participated in gymnastics, swimming, and soccer. Her favorite foods are mashed potatoes and LaFesta pizza back in New Hampshire.",
                ""));
        divers.add(new DtoDiver("http://www.usadiving.org/wp-content/uploads/2013/09/Kassidy-Cook-240x300.jpg",
                "http://fandaily.info/wp-content/uploads/2012/07/Kassidy-Cook-Tom-Daley-Girlfriend-photos1.jpg",
                "Kassidy",
                "Cook",
                "5’ 3”",
                "May 9, 1995",
                "Plantation, Fla.",
                "The Woodlands, Texas",
                "Stanford, Calif.",
                "Stanford University",
                "",
                "Stanford Diving",
                "",
                "Rick Schavone",
                nationalTeamMemeber("2010, 2011, 2012"),
                "Kassidy is the daughter of Kevin and Laura Cook. She has five siblings: Kevin, Kara, Kelsey, Kylie and Kendall. Kassidy started diving at the age of four, and her sister, Kara, was a diver at Purdue University. Kassidy enjoys sports of all kinds and trains five hours a day, six days a week. The National Interscholastic Swim Coaches Association (NISCA) named her the 2010 high school girls national champion in its diving All-American program. Her favorite meal is steak, and she is a fan of Lord of the Rings movies. Kassidy’s lucky number is thirteen and she claims she can recite any Harry Potter spell.",
                ""));
        divers.add(new DtoDiver("http://www.usadiving.org/wp-content/uploads/2013/09/Kristian-Ipsen-240x300.jpg",
                "http://www4.pictures.zimbio.com/gi/Kristian+Ipsen+FINA+World+Championships+Diving+5BSzrvHkSegl.jpg",
                "Kristian",
                "Ipsen",
                "5’ 7”",
                "October 20, 1992",
                "Walnut Creek, Calif.",
                "Clayton, Calif.",
                "Stanford, Calif.",
                "Stanford University",
                "",
                "Stanford Diving",
                "",
                "Rick Schavone",
                nationalTeamMemeber("2006, 2008, 2009, 2010, 2011, 2012, 2013"),
                "Kristian is the son of Kent and Yvette Ipsen. He has a younger sister, Lauren. Kristian has been diving since 1998 and was featured in Sports Illustrated’s Faces in the Crowd. At age 8, he became the youngest diver to final on all three boards at the Junior National Championships and later became the youngest diver to win a junior national title. He dove for coach Phil Tonne at Diablo Divers before starting his collegiate career in the fall of 2011. In the summer, Kristian works at his family’s restaurants (Skipolini’s Pizza).",
                ""));
        divers.add(new DtoDiver("http://www.usadiving.org/wp-content/uploads/2013/09/Laura-Ryan.jpg",
                "http://www4.pictures.zimbio.com/gi/Laura+Ryan+USA+Diving+Grand+Prix+FBC-JfjEmBNl.jpg",
                "Laura",
                "Ryan",
                "5’ 5”",
                "July 4, 1992",
                "Burnsville, Minn.",
                "Elk River, Minn.",
                "Athens, Ga.",
                "University of Georgia",
                "",
                "Georgia Diving Club",
                "Athens, Ga.",
                "Dan Laak",
                nationalTeamMemeber("2010, 2011, 2012, 2013, 2014"),
                "Laura is the daughter of Gary and Barb Ryan. She has two siblings. She started diving when she was 12 years old and had shoulder surgery in the summer of 2008 that kept her out of the pool for 9 months. Laura enjoys boating, camping and skiing, and loves Italian food.",
                ""));
        divers.add(new DtoDiver("http://www.usadiving.org/wp-content/uploads/2013/11/Maren-Taylor1.jpg",
                "http://www3.pictures.zimbio.com/gi/Maren+Taylor+FINA+World+Championships+Diving+opRejRa2x5Cl.jpg",
                "Maren",
                "Taylor",
                "5’ 5”",
                "August 2, 1991",
                "Reston, Va.",
                "Arlington, Va.",
                "Austin, Texas",
                "University of Texas",
                "Biology and History",
                "Longhorn Aquatics",
                "",
                "Matt Scoggin",
                nationalTeamMemeber("2013, 2014"),
                "Maren is the daughter of Tony and Pamela Taylor and has one brother, Reid. She started diving in 1996 and was also a gymnast until her sophomore year in high school. Her favorite dive is 405B. She was away from diving for nearly a year after dislocating her elbow at the 2011 NCAA Championships. Maren would like to become an environmental lawyer. When she is not on the springboards, Maren enjoys scuba diving and skiing.",
                ""));
        divers.add(new DtoDiver("http://www.usadiving.org/wp-content/uploads/2013/10/Michael-Hixon.jpg",
                "http://www4.pictures.zimbio.com/gi/Michael+Hixon+Youth+Olympics+Day+8+Diving+hn_E5W9NCiQl.jpg",
                "Michael",
                "Hixon",
                "5’ 8”",
                "July 16, 1994",
                "Amherst, Mass.",
                "Amherst, Mass.",
                "Austin, Texas",
                "University of Texas",
                "",
                "Longhorn Aquatics",
                "",
                "Matt Scoggin",
                nationalTeamMemeber("2011, 2012, 2013, 2014"),
                "Michael is the son of Mandy and David Hixon. He has an older brother, Matthew, and started diving when he was 7 years old. His mom dove at Ohio State and is the diving coach at the University of Massachusetts. Michael’s dad is the basketball coach at Amherst College. His favorite movie is Boondock Saints. He enjoys basketball, golf, running and biking, and he would like to be a diving coach when he is older. Michael began attending the University of Texas in fall  2013.",
                ""));
        divers.add(new DtoDiver("http://www.usadiving.org/wp-content/uploads/2013/09/Nick-McCrory-240x300.jpg",
                "http://www4.pictures.zimbio.com/gi/Nick+McCrory+FINA+Diving+World+Series+2012+8nfvbbpq0opl.jpg",
                "Nick",
                "McCrory",
                "5’ 10”",
                "August 9, 1991",
                "Durham, N.C.",
                "Chapel Hill, N.C.",
                "Bloomington, Ind.",
                "Duke University",
                "",
                "",
                "",
                "Drew Johansen",
                nationalTeamMemeber("2007, 2008, 2009, 2010, 2011, 2012, 2014"),
                "Nick is the son of Doug and Ana McCrory.He has one younger brother, Lucas. His uncle, Gordon Downie, won a bronze medal in swimming at the 1976 Olympics for Great Britain (800-meter free relay). Nick began diving in 1998.  His brother is a swimmer and will compete for Team USA at the 2014 Pan Pacific Para-Swimming Championships. After graduating from Duke University in 2014, Nick moved to Bloomington, Ind., to resume training with coach Drew Johansen, who coached him at the Olympic Games. Nick plans to attend medical school and would like to become a doctor, like his father. He’s active in the Little People of America with his brother Lucas, and describes himself as arachnophobic, ambitious and level-headed. He enjoys fishing.",
                ""));
        divers.add(new DtoDiver("http://www.usadiving.org/wp-content/uploads/2013/11/Samuel-Dorman.jpg",
                "http://image.cdnllnwnl.xosnetwork.com/pics33/640/SU/SUQYNEGYYMBCUYQ.20130819144220.jpg",
                "Sam",
                "Dorman",
                "5’ 9”",
                "August 30, 1991",
                "Tempe, Ariz.",
                "Tempe, Ariz.",
                "Coral Gables, Fla.",
                "University of Miami",
                "Mechanical Engineering",
                "Miami Diving",
                "",
                "Randy Ableman",
                nationalTeamMemeber("2013, 2014"),
                "Sam is the son of Marla Dorman, a lab technician, and Paul Dorman, a P.E. teacher and has an older brother, Ben. Sam began diving at the age of eight, competed in his first junior nationals in 2004 and in his first senior nationals in 2008. His favorite dive is a 109C and during meets Sam tries to laugh and relax. When he’s not diving, Sam enjoys eating pizza and working on his car.",
                ""));
        divers.add(new DtoDiver("http://www.usadiving.org/wp-content/uploads/2013/11/Samantha-Pickens.jpg",
                "http://www4.pictures.zimbio.com/gi/Samantha+Pickens+FINA+World+Championships+tvQjwh64n1Il.jpg",
                "Samantha",
                "Pickens",
                "",
                "July 4, 1991",
                "",
                "Murrysville, Pa.",
                "Tucson, Ariz.",
                "University of Arizona",
                "",
                "Tucson Diving Team",
                "",
                "Omar Ojeda",
                nationalTeamMemeber("2013, 2014"),
                "Samantha is the daughter of Jack and Debra Pickens and she has an older brother, David. Samantha began diving when she was 12 and now trains five hours a day, six days a week. Her favorite dive is 5152B on 3-meter. Samantha won the NCAA title on 1-meter in 2013. She is a member of Project Focus, which helps disabled kids in a college setting. Samantha is majoring in psychology and hopes to become a sport psychologist. Away from the pool, she enjoys skiing, shopping and cooking. She also loves playing with big dogs (she has a 130-pound St. Bernard).",
                ""));
        divers.add(new DtoDiver("http://www.usadiving.org/wp-content/uploads/2013/11/Samantha-Bromberg.jpg",
                "http://cache4.asset-cache.net/gc/168618317-samantha-bromberg-of-the-usa-dives-during-gettyimages.jpg?v=1&c=IWSAsset&k=2&d=GkZZ8bf5zL1ZiijUmxa7QSujrmB9NR4VqtQctGF%2BUNDYPjpRVfiYxpfi%2FmWc91l1",
                "Samantha “Murphy”",
                "Bromberg",
                " 5’1″",
                "July 12, 1995",
                "",
                "Bexley, Ohio",
                "Austin, Texas",
                "University of Texas",
                "",
                "Longhorn Aquatics",
                "",
                "Matt Scoggin",
                nationalTeamMemeber("2013, 2014"),
                "Murphy is the daughter of Danny and Karen Bromberg. She has an older sister, Jennie, and a younger brother, David. She began diving at age nine and now trains 3 to 4 hours a day, five days a week. She says the most difficult part of training is trying to balance diving with school and her social life. When she’s not diving, Murphy likes to hang out with friends. She describes herself as crazy, fun and hardworking.",
                ""));
        divers.add(new DtoDiver("http://www.usadiving.org/wp-content/uploads/2013/09/Steele-Johnson.jpg",
                "http://www.teamusa.org/~/media/TeamUSA/Diving/johnson_steele_300x375_2.jpg",
                "Steele",
                "Johnson",
                "6’0″",
                "June 16, 1996",
                "Indianapolis, Ind.",
                "Carmel, Ind.",
                "West Lafayette, Ind.",
                "Purdue University",
                "",
                "Boiler Diving Academy",
                "",
                "Adam Soldati",
                nationalTeamMemeber("2010, 2011, 2012, 2013, 2014"),
                "Steele is the son of Bill and Jill Johnson. He has an older brother and a younger sister.His brother, Race, plays football for Purdue University, the same school that Steele will begin his collegiate career in the fall of 2014. Steele started diving when he was 7 years old, and his favorite dive is 407C on 10-meter. Steele enjoys playing guitar and making films (he has several YouTube Channels). He likes to listen to post-hardcore music and says he is a pro at Super Smash Bros. He is also actively involved in his church. His favorite meal is cheeseburger and french fries. His dad played baseball at Sam Houston State and his mom was a professional singer and actress.",
                ""));
        divers.add(new DtoDiver("http://www.usadiving.org/wp-content/uploads/2013/09/Toby-Stanley-2-of-2.jpg",
                "http://0.tqn.com/d/diving/1/5/m/M/-/-/Toby_Stanley.jpg",
                "Toby",
                "Stanley",
                "5’6″",
                "April 9, 1992",
                "",
                "Conway, Ark.",
                "Fishers, Ind.",
                "",
                "",
                "Unattached",
                "",
                "John Wingfield",
                nationalTeamMemeber("2010, 2011, 2012, 2013, 2014"),
                "Toby is the son of Ronald and Mackey Stanley. He has two older siblings, Molly and Andy.Toby started diving at age 13 and was a springboard diver until he saw a video of four-time Olympic gold medalist Greg Louganis diving platform and decided that was his calling. (There were no platforms in his area, so until seeing that video, he didn’t know platform diving was a possibility.) Because there were no platforms near his hometown, he would drive five hours round-trip, once a month to train on a tower for a few days until moving to the National Training Center in Indianapolis in 2009. He quickly progressed to become one of the top 10-meter platform divers in the country. Toby was also a gymnast for seven years and plays the clarinet.",
                ""));
        divers.add(new DtoDiver("http://www.usadiving.org/wp-content/uploads/2013/11/Tori-Lamp-241x300.jpg",
                "http://heraldnewstn.com/wp-content/uploads/2012/04/Tori-Lamp.jpeg",
                "Tori",
                "Lamp",
                "5’8″",
                "May 2, 1991",
                "Knoxville, Tenn.",
                "Knoxville, Tenn.",
                "Knoxville, Tenn.",
                "University of Tennessee",
                "",
                "University of Tennessee",
                "",
                "Dave Parrington",
                nationalTeamMemeber("2009, 2012, 2013, 2014"),
                "Tori is the daughter of Danny and Diane Lamp. She has an older sister, Jennifer. Her dad was also an athlete and twice qualified for the U.S. Olympic Team Trials for track and field. A former level 10 gymnast, Tori started diving in 2004 and now trains 3-4 hours a day, 6 days a week. She had knee surgery in 2009 and has been hampered with injuries the past few years.Tori is majoring in kinesiology and would like to become a pediatric occupational therapist. She enjoys video-editing and playing piano (she started playing when she was 7). Tori’s favorite dive is 6243D on 10-meter and she describes herself as competitive, determined and caring.",
                ""));
        divers.add(new DtoDiver("http://www.usadiving.org/wp-content/uploads/2013/10/Troy-Dumais1.jpg",
                "http://www3.pictures.zimbio.com/gi/Troy+Dumais+Olympics+Day+10+Diving+Q0UQrHSGLuUl.jpg",
                "Troy",
                "Dumais",
                "5’6″",
                "January 21, 1980",
                "Ventura, Calif.",
                "Ventura, Calif.",
                "Austin, Texas",
                "University of Texas",
                "B.S. Exercise Science ",
                "Longhorn Aquatics",
                "Austin, Texas",
                "Matt Scoggin",
                nationalTeamMemeber("1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014"),
                "Troy is the son of Marc and Kathleen Dumais. He has three brothers, Justin (born 8/13/78), Brice (born 4/23/81) and Dwight (born 6/23/86), as well as one sister, Leanne (born 7/2/84). All four of his siblings have also been divers. Justin was on the 2004 Olympic team and previously trained under coaches Van Austin, Tom Scotty and Jeff Shaffer. Troy’s father was a professional French Canadian hockey player and tennis player. In addition to diving, Troy has played football, hockey, tennis, basketball and baseball. He enjoys music, cars, movies, playing games, working out and hanging out with friends, and he plans to become a physical therapist. Troy has been diving for 24 years, trains eight hours a day and has no favorite dives because he likes them all. He’s also a four-time Olympian.",
                ""));
    }

    public ArrayList<DtoDiver> getDivers() {
        return divers;
    }

    private ArrayList<String> nationalTeamMemeber(String years) {
        ArrayList<String> temp = new ArrayList<String>();
        String[] temps = years.split(",");
        for (String str : temps) {
            temp.add(str);
        }
        return temp;
    }
}
